Frontend/HotelProject.WebUI/ViewComponents/Home/BookingViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace HotelProject.WebUI.ViewComponents.Home
{
    public class BookingViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

Frontend/HotelProject.WebUI/ViewComponents/Home/CarouselViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace HotelProject.WebUI.ViewComponents.Home
{
    public class CarouselViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

Frontend/HotelProject.WebUI/Views/Shared/_CssPartialView.cshtml
<link href="~/frontEnd/img/favicon.ico" rel="icon">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600;700&family=Montserrat:wght@400;500;600;700&display=swap" rel="stylesheet">
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/@@sweetalert2/theme-bulma@4/bulma.css" rel="stylesheet">
<link href="~/frontEnd/lib/animate/animate.min.css" rel="stylesheet">
<link href="~/frontEnd/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
<link href="~/frontEnd/lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css" rel="stylesheet" />
<link href="~/frontEnd/css/bootstrap.min.css" rel="stylesheet">
<link href="~/frontEnd/css/style.css" rel="stylesheet">

Frontend/HotelProject.WebUI/Views/Shared/_FooterPartialView.cshtml
<div class="container-fluid bg-dark text-light footer wow fadeIn" data-wow-delay="0.1s">
    <div class="container pb-5">
        <div class="row g-5">
            <div class="col-md-6 col-lg-4">
                <div class="bg-primary rounded p-4">
                    <a href="index.html"><h1 class="text-white text-uppercase mb-3">Hotelier</h1></a>
                    <p class="text-white mb-0">
                        Download <a class="text-dark fw-medium" href="https://htmlcodex.com/hotel-html-template-pro">Hotelier – Premium Version</a>, build a professional website for your hotel business and grab the attention of new visitors upon your site’s launch.
                    </p>
                </div>
            </div>
            <div class="col-md-6 col-lg-3">
                <h6 class="section-title text-start text-primary text-uppercase mb-4">Contact</h6>
                <p class="mb-2"><i class="fa fa-map-marker-alt me-3"></i>123 Street, New York, USA</p>
                <p class="mb-2"><i class="fa fa-phone-alt me-3"></i>+012 345 67890</p>
                <p class="mb-2"><i class="fa fa-envelope me-3"></i>info@example.com</p>
                <div class="d-flex pt-2">
                    <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-twitter"></i></a>
                    <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-facebook-f"></i></a>
                    <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-youtube"></i></a>
                    <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-linkedin-in"></i></a>
                </div>
            </div>
            <div class="col-lg-5 col-md-12">
                <div class="row gy-5 g-4">
                    <div class="col-md-6">
                        <h6 class="section-title text-start text-primary text-uppercase mb-4">Company</h6>
                        <a class="btn btn-link" href="">About Us</a>
                        <a class="btn btn-link" href="">Contact Us</a>
                        <a class="btn btn-link" href="">Privacy Policy</a>
                        <a class="btn btn-link" href="">Terms & Condition</a>
                        <a class="btn btn-link" href="">Support</a>
                    </div>
                    <div class="col-md-6">
                        <h6 class="section-title text-start text-primary text-uppercase mb-4">Services</h6>
                        <a class="btn btn-link" href="">Food & Restaurant</a>
                        <a class="btn btn-link" href="">Spa & Fitness</a>
                        <a class="btn btn-link" href="">Sports & Gaming</a>
                        <a class="btn btn-link" href="">Event & Party</a>
                        <a class="btn btn-link" href="">GYM & Yoga</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="copyright">
            <div class="row">
                <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                    &copy; <a class="border-bottom" href="#">Your Site Name</a>, All Right Reserved.

                    <!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
                    Designed By <a class="border-bottom" href="https://htmlcodex.com">HTML Codex</a>
                </div>
                <div class="col-md-6 text-center text-md-end">
                    <div class="footer-menu">
                        <a href="">Home</a>
                        <a href="">Cookies</a>
                        <a href="">Help</a>
                        <a href="">FQAs</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Frontend/HotelProject.WebUI/Views/Shared/_JsPartialView.cshtml
 <!-- JavaScript Libraries -->
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.js"></script>
<script src="~/frontEnd/lib/wow/wow.min.js"></script>
<script src="~/frontEnd/lib/easing/easing.min.js"></script>
<script src="~/frontEnd/lib/waypoints/waypoints.min.js"></script>
<script src="~/frontEnd/lib/counterup/counterup.min.js"></script>
<script src="~/frontEnd/lib/owlcarousel/owl.carousel.min.js"></script>
<script src="~/frontEnd/lib/tempusdominus/js/moment.min.js"></script>
<script src="~/frontEnd/lib/tempusdominus/js/moment-timezone.min.js"></script>
<script src="~/frontEnd/lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js"></script>

<!-- Template Javascript -->
<script src="~/frontend/js/main.js"></script>

Frontend/HotelProject.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Hotelier @(ViewData["Title"] == null ? "" : $" | {ViewData["Title"]}") </title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    @await Html.PartialAsync("_CssPartialView")
    @if (IsSectionDefined("Css"))
    {
        @await RenderSectionAsync("Css",false)
    }
</head>

<body>
    <div class="container-fluid bg-white p-0">
        <!-- Spinner Start -->
        <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only">Yükleniyor...</span>
            </div>
        </div>
        <!-- Spinner End -->
        <!-- Header Start -->
        @await Html.PartialAsync("_NavbarPartialView")
        <!-- Header End -->
        <!-- Carousel Start -->
        @await Component.InvokeAsync("Carousel")
        <!-- Carousel End -->
        <!-- Booking Start -->
        @await Component.InvokeAsync("Booking")
        <!-- Booking End -->
        @RenderBody()
        <!-- Newsletter Start -->
        @await Html.PartialAsync("_NewsletterPartialView.cshtml");
        <!-- Newsletter Start -->
        <!-- Footer Start -->
        @await Html.PartialAsync("_FooterPartialView")
        <!-- Footer End -->
        <!-- Back to Top -->
        <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
    </div>

    @await Html.PartialAsync("_JsPartialView")
    @if (IsSectionDefined("Scripts"))
    {
        @await RenderSectionAsync("Scripts",false)
    }
</body>

</html>

Frontend/HotelProject.WebUI/Views/Shared/_NavbarPartialView.cshtml
<div class="container-fluid bg-dark px-0">
    <div class="row gx-0">
        <div class="col-lg-3 bg-dark d-none d-lg-block">
            <a asp-controller="Home" asp-action="Index" asp-area="" class="navbar-brand w-100 h-100 m-0 p-0 d-flex align-items-center justify-content-center">
                <h1 class="m-0 text-primary text-uppercase">Hotelier</h1>
            </a>
        </div>
        <div class="col-lg-9">
            <div class="row gx-0 bg-white d-none d-lg-flex">
                <div class="col-lg-7 px-5 text-start">
                    <div class="h-100 d-inline-flex align-items-center py-2 me-4">
                        <i class="fa fa-envelope text-primary me-2"></i>
                        <p class="mb-0">hotelapi@example.com</p>
                    </div>
                    <div class="h-100 d-inline-flex align-items-center py-2">
                        <i class="fa fa-phone-alt text-primary me-2"></i>
                        <p class="mb-0">+090 345 6789</p>
                    </div>
                </div>
                <div class="col-lg-5 px-5 text-end">
                    <div class="d-inline-flex align-items-center py-2">
                        <a class="me-3" href=""><i class="fab fa-facebook-f"></i></a>
                        <a class="me-3" href=""><i class="fab fa-twitter"></i></a>
                        <a class="me-3" href=""><i class="fab fa-linkedin-in"></i></a>
                        <a class="me-3" href=""><i class="fab fa-instagram"></i></a>
                        <a class="" href=""><i class="fab fa-youtube"></i></a>
                    </div>
                </div>
            </div>
            <nav class="navbar navbar-expand-lg bg-dark navbar-dark p-3 p-lg-0">
                <a href="index.html" class="navbar-brand d-block d-lg-none">
                    <h1 class="m-0 text-primary text-uppercase">Hotelier</h1>
                </a>
                <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                    <div class="navbar-nav mr-auto py-0">
                        <a asp-controller="Home" asp-action="Index" asp-area="" class="nav-item nav-link active">Anasayfa</a>
                        <a asp-controller="About" asp-action="Index" asp-area="" class="nav-item nav-link">Hakkımızda</a>
                        <a asp-controller="Service" asp-action="Index" asp-area="" class="nav-item nav-link">Hizmetlerimiz</a>
                        <a asp-controller="Room" asp-action="Index" asp-area="" class="nav-item nav-link">Odalarımız</a>
                        <div class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Sayfalar</a>
                            <div class="dropdown-menu rounded-0 m-0">
                                <a asp-controller="Booking" asp-action="Index" asp-area="" class="dropdown-item">Rezervasyon</a>
                                <a asp-controller="Team" asp-action="Index" asp-area="" class="dropdown-item">Ekibimiz</a>
                                <a asp-controller="Testimonial" asp-action="Index" asp-area="" class="dropdown-item">Referanslarımız</a>
                            </div>
                        </div>
                        <a asp-controller="Contact" asp-action="Index" asp-area="" class="nav-item nav-link">İletişim</a>
                    </div>
                </div>
            </nav>
        </div>
    </div>
</div>

Frontend/HotelProject.WebUI/Views/Shared/_NewsletterPartialView.cshtml
<div class="container newsletter mt-5 wow fadeIn" data-wow-delay="0.1s">
    <div class="row justify-content-center">
        <div class="col-lg-10 border rounded p-1">
            <div class="border rounded text-center p-1">
                <div class="bg-white rounded text-center p-5">
                    <h4 class="mb-4">Haber bültenimize <span class="text-primary text-uppercase">Kayıt Ol!</span></h4>
                    <div class="position-relative mx-auto" style="max-width: 400px;">
                        <input id="newsMail" class="form-control w-100 py-3 ps-4 pe-5" type="text" placeholder="Email adresinizi giriniz" required>
                        <button id="signUpNews" type="button" class="btn btn-primary py-2 px-3 position-absolute top-0 end-0 mt-2 me-2">Kayıt Ol</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>